### ISSUE TITLE
Please add a check to not equip broken Elytras.

### ISSUE THREAD

**Issue by grisuIIARCHLINUX** [glitchifyed/quick_hotkeys#1]
I was flying in the end when my elytra broke, i had 3 in my inventory i pressed my elytra hotkey twice but it just put the broken one back on. Now my stuff is gone. Well its not that bad, i dont have any hobbies so i just regrind my equip rn but it would be a nice QoL

**Comment by glitchifyed** [comment]
Fixed in v1.0.2.
