### ISSUE TITLE
When you press the x button, the totem is not put on in the second hand

### ISSUE THREAD

**Issue by jdisi2k29** [glitchifyed/quick_hotkeys#2]
I installed the mod, when the totems are in the inventory, and the second hand is empty, then I press the X button, a sound is made and nothing happens, what is this why?

**Comment by glitchifyed** [comment]
Are you on a server or in singleplayer? A multiplayer server may or may not have an anticheat that might prevent the mod from working.

**Comment by ImNotSawiq** [comment]
> Are you on a server or in singleplayer? A multiplayer server may or may not have an anticheat that might prevent the mod from working.

I play in single player mode, the button to change the bib to elites works by the way, but there are no totems

**Comment by glitchifyed** [comment]
This issue **should** be fixed in the latest release of the mod on Modrinth.
