### ISSUE TITLE
Doesnt seem to work on servers on 1.20.4 anymore

### ISSUE THREAD

**Issue by grisuIIARCHLINUX** [glitchifyed/quick_hotkeys#4]
Trying to equip a armor chest piece only work when the chest piece is in hotbar, switching to an elytra only work when the better elytra is in your hotbar. Totems dont seem to work correctly either. This shouldnt be a server issue since it runs almost vanilla, if you need log or anything just ask since i dont know what i need to attach.

**Comment by glitchifyed** [comment]
I'm currently unsure of what is causing these issues sadly.

**Comment by grisuIIARCHLINUX** [comment]
Any progress/news on this bug?

**Comment by notIkibo** [comment]
Noooo, it's such a great clientside mod you could've used on vanilla mc QwQ

Though I still hope you eventually patch it. Something like this is very missed

**Comment by glitchifyed** [comment]
I may do it one day if I get back into modding

**Comment by glitchifyed** [comment]
I believe the issue was created by a change Mojang seemed to have made on the server which doesn't allow me to switch slots inside the inventory anymore. I am currently looking at alternative code for this.
