### ISSUE TITLE
Possibility for 1.21?

### ISSUE THREAD

**Issue by Chief0609** [glitchifyed/quick_hotkeys#5]
I absolutely love this mod. makes gameplay just a little bit easier. but at this time there is no 1.21 version of this mod and I am wondering if there is a plan to make one?

**Comment by glitchifyed** [comment]
Sorry I didn't see this for a few weeks. I haven't gotten around to updating the mod for 1.21 yet mainly because I personally have no use for my own mod anymore. I have seen potential alternatives that may behave even more autonomously for quick-equipping elytra these days.

**Comment by glitchifyed** [comment]
So I am currently in the progress of updating the mod to the latest version, however I am experiencing a major problem. I believe it was Minecraft 1.20.5 that changed a few things in the code that now don't allow the main feature of the mod (swapping elytra without opening the inventory) to work at all.
