### ISSUE TITLE
the 1.21 versions dont work because they require a version of fabric api that doesnt exist for 1.21

### ISSUE THREAD

**Issue by janga123** [glitchifyed/quick_hotkeys#6]

**Comment by glitchifyed** [comment]
The mod requires Fabric API version 0.103, which seems to not appear on third party launchers, such as Prism Launcher at the moment. But if you filter your search for 1.21.x, you can still use a 1.21.1 version for 1.21.

**Comment by janga123** [comment]
ok thanks ill try that
